"""
Utilities to simulate the discrete scale recurrence generated by repeated
applications of ``U_alpha = exp(i * alpha * Delta)`` on a periodic lattice.

The public API exposes the simulator, common initial states, and helper
metrics so experiments can be scripted or driven from the command line.
"""

from .simulator import (
    DiscreteScaleRecurrenceSimulator,
    NoiseModel,
    SimulationResult,
)
from . import initial_states
from . import metrics

__all__ = [
    "DiscreteScaleRecurrenceSimulator",
    "NoiseModel",
    "SimulationResult",
    "initial_states",
    "metrics",
]
